name: pretrain/scannet25k_lr_decay
neptune_project_name: ASL/MT-JonasFrey
offline_mode: true
timestamp: true
weights_restore: false
checkpoint_restore: false
checkpoint_load: None
lr: 0.001
tag_list:
  - scannet
  - pretrain_25k
supervisor:
  # Experiment Settings
  start_task: 0
  stop_task: 1

meters:
  train: False
  val_0: False
  val_1: False
  log_val_dataloader_1: [0,49]
  log_val_dataloader_0: [49]
  
task_specific_early_stopping:
  active: True
  cfg:
    patience: 2000
    timelimit_in_min: 520
    verbose: true
    max_epoch_count: 1000

lr_scheduler:
  active: true
  name: POLY
  poly_cfg:
    power: 0.9
    max_epochs: 159
    target_lr: 1.0e-06
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 100
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
loader:
  pin_memory: true
  batch_size: 8
  shuffle: true
  num_workers: 16
replay:
  cfg_ensemble:
    active: False
visu:
  every_n_epochs: 1
  log_training_metric_every_n_epoch: 1
  images:
    train: 1
    val: 1
    test: 1
  log_ref_weights_grad_every_n_steps: 10000

model:
  name: Fast-SCNN
  input_size:
  - 320
  - 640
  cfg:
    num_classes: 40
    aux: false
    extraction:
      active: false
      layer: learn_to_down

loss:
  aux_label_factor: 1
  soft_aux_label_factor: 1
  

task_generator:
  name: scannet
  mode: scannet_25k
  cfg:    
    copy_to_template:
      output_size: 
      - 320
      - 640
      label_setting: default

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    save_last: true
    save_top_k: 20

lr_monitor:
  cfg:
    logging_interval: step