name: scannet25k_24h_lr_decay_from_scratch/scannet25k_24h_lr_decay_from_scratch
offline_mode: true
timestamp: true
weights_restore: false
checkpoint_restore: false
# checkpoint_load: /home/jonfrey/Results/created_labels/created_labels/2021-05-26T14:12:25_prob09/task1-epoch=07--step=012381.ckpt
checkpoint_load: scannet25k_24h/2021-06-01T14:48:33_scannet25k_24h/task0_store_epoch_145.ckpt
lr: 0.001
tag_list:
  - scannet
  - pretrain_25k
  - half_res

supervisor:
  # Experiment Settings
  start_task: 0
  stop_task: 0

task_specific_early_stopping:
  active: True
  cfg:
    patience: 2000
    timelimit_in_min: 530
    verbose: True

teaching:
  active: False
  soft_labels: False
  soft_labels_weight: 10
  loss_function: MSE

# Standard Setting
lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 150
    target_lr: 1.0e-06
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 10
  max_epochs: 1000
  gpus: -1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  #accelerator: ddp

loader:
  pin_memory: true
  batch_size: 8
  shuffle: true
  num_workers: 20
replay:
  cfg_ensemble:
    active: True
    probs: 0.2
  cfg_rssb:
    elements: 1000
    bins: -1
visu:
  every_n_epochs: 1
  log_training_metric_every_n_epoch: 1
  images:
    train: 1
    val: 1
    test: 1
  log_ref_weights_grad_every_n_steps: 10000

model:
  name: Fast-SCNN
  input_size:
    - 320
    - 640
  cfg:
    num_classes: 40
    aux: false
    extraction:
      active: false
      layer: 'learn_to_down'
  freeze:
    active: false
    mask:
      - false
      - false
      - false 
      - false

task_generator:
  name: scannet
  mode: scannet_25k
  cfg:
    scannet_auxilary_labels:
      label_setting: default

    scannet_scenes:
      number_of_tasks: 4
      scenes_per_task: 5
      
    copy_to_template:
      output_size: 
      - 320
      - 640
      label_setting: default

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001
cb_checkpoint:
  active: true
  nameing: 1
  cfg:
    verbose: true
    monitor: train_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 20
lr_monitor:
  cfg:
    logging_interval: epoch

label_generation:
  active: True
  identifier: labels_scannet25k_24h_lr_decay_from_scratch
  confidence: 0
  scenes:
    - scene0000_00
    - scene0000_01
    - scene0000_02
    - scene0001_00
    - scene0001_01
    - scene0002_00
    - scene0002_01
    - scene0003_00
    - scene0003_01
    - scene0003_02
    - scene0004_00
    - scene0005_00
    - scene0005_01
    - scene0006_00
    - scene0006_01
    - scene0006_02
    - scene0007_00
    - scene0008_00
    - scene0009_00
    - scene0009_01
    - scene0009_02

move_datasets:
  - env_var: scannet
  - env_var: scannet_frames_25k